# Generated by Django 4.1.6 on 2023-02-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_band_active_band_biography_band_genre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="band",
            name="genre",
            field=models.CharField(
                choices=[
                    ("HH", "Hip Hop"),
                    ("SP", "Synth Pop"),
                    ("AR", "Alternative Rock"),
                ],
                max_length=5,
            ),
        ),
    ]
